print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)

print("Simon")
print("Diez")
print("Colombia")
print("Estoy disfrutando 30 días de Python")

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(["Simon","Python","Colombia"]))
print(type("Simon"))
print(type("Diez"))
print(type("Colombia"))
